version: '3.1'

services:

  server:
    build: ./server
    container_name: generalorderserver
    environment:
      - NODE_ENV=development   
    ports:
      - 5001:5000
    restart: always
  
  client:
    build: ./client
    container_name: generalorderclient
    environment:
      - NODE_ENV=development
    ports:
      - 3001:3000
    restart: always
    volumes:
      - '.:/app'
      - '/app/node_modules'