version: "3.1"
services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: gorder-dynamodb
    networks:
      - backend
    ports:
      - 8000:8000

  # lambda:
  #   image: amazon/lambda-build-node10.x
  #   container_name: gorder-lambda
  #   command: sam local start-lambda
  #   ports:
  #     - 7000:7000

  # s3:
  #   image: scality/s3server
  #   container_name: gorder-s3
  #   ports:
  #     - 6000:6000

  server:
    image: rchillard/generalorder-server:0.1
    depends_on:
      - "dynamodb"
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.5"
          memory: 50M
      restart_policy:
        condition: on-failure
    environment:
      - NODE_ENV=development
    networks:
      - backend
    ports:
      - 4000:3000

networks:
  backend:
  # client:
  #   build: ./client
  #   container_name: gorder-client
  #   environment:
  #     - NODE_ENV=development
  #   ports:
  #     - 3001:3000
  #   volumes:
  #     - ".:/app"
  #     - "/app/node_modules"
